#!/usr/bin/env ruby
# frozen_string_literal: true

require "yaml"
require "fileutils"
require_relative "lib/envelope"
require_relative "lib/cli"

# BuildAgents renders a directory of agent definitions from templates and
# shared blocks, and lints the routing between them (ADR-0019).
#
# Layout, all under one directory (`--dir`, default ./agents):
#
#   <name>.md.in       a template: frontmatter, then prose in which a line
#                      of the form `@include <block>` stands for a block
#   blocks/<block>.md  a shared block, spliced verbatim where included
#   routing.yml        `blocks: {<block>: [<name>, ...]}` - which agents
#                      carry which block; the authority on who shares what
#   <name>.md          the generated definition, committed beside its
#                      template so an installer that symlinks *.md and a
#                      skill that names an agent keep working unchanged
#
# The generated file is the template with one banner line after its
# frontmatter and every include replaced by its block. The banner sits in
# the body rather than inside the frontmatter because the frontmatter is
# parsed by the harness that loads the agent, and a comment there would
# depend on that parser tolerating one.
#
# Lint, run in every mode, refuses the build before anything is written:
#
#   dangling_include      a template includes a block with no file
#   unauthorized_include  a template includes a block routing.yml does not
#                         route to that agent
#   missing_include       routing.yml routes a block to an agent whose
#                         template never includes it
#   orphan_block          a block file routing.yml never names
#   dangling_route        routing.yml names a block with no file
#   unknown_agent         routing.yml names an agent with no template
#   nested_include        a block contains an include line (blocks are
#                         leaves; nothing expands inside one)
#   no_frontmatter        a template does not open with a frontmatter block
#   ungenerated_agent     a <name>.md with no <name>.md.in - every agent in
#                         the directory is generated, or it is a mistake
#
# `--check` adds `stale_generated` and `missing_generated` (a generated file
# that differs from, or is absent for, its template) and writes nothing;
# it is what the kit's own suite runs. Without it, files that differ are
# written (`--dry-run` lists them under `commands` instead). Pure filesystem
# logic: no Sh, no manifest.
module BuildAgents
  TEMPLATE_EXT = ".md.in"
  GENERATED_EXT = ".md"
  BLOCKS_SUBDIR = "blocks"
  ROUTING_FILE = "routing.yml"
  DEFAULT_DIR = "agents"

  INCLUDE = /\A@include[ \t]+([A-Za-z0-9][A-Za-z0-9_-]*)[ \t]*\z/.freeze
  FRONTMATTER_FENCE = /\A---[ \t]*\z/.freeze

  # One line, HTML comment so it is inert in the rendered prose. Names the
  # template it came from so a reader who lands in the generated file finds
  # the file to edit without knowing the scheme.
  def self.banner(name)
    "<!-- DO NOT EDIT: generated by build_agents.rb from #{name}#{TEMPLATE_EXT} " \
      "and blocks/ (see routing.yml); edit those and rebuild -->"
  end

  Template = Struct.new(:name, :path, :content, :includes, :frontmatter_end, keyword_init: true)

  # Everything the directory says, read once. Lint and render are pure
  # functions over it.
  class Set
    attr_reader :dir, :templates, :blocks, :routing, :routing_error

    def initialize(dir)
      @dir = dir
      @templates = read_templates
      @blocks = read_blocks
      @routing, @routing_error = read_routing
    end

    def template(name)
      templates.find { |t| t.name == name }
    end

    def generated_path(name)
      File.join(dir, "#{name}#{GENERATED_EXT}")
    end

    def generated_names
      Dir.glob(File.join(dir, "*#{GENERATED_EXT}")).sort.map { |p| File.basename(p, GENERATED_EXT) }
    end

    # [[code, message], ...] in a stable order. Empty means the build may
    # proceed. The routing file is checked first: without it every include
    # is unauthorized and every block an orphan, which is noise, not a
    # diagnosis.
    def lint
      return [routing_error] if routing_error

      findings = []
      templates.each do |t|
        findings << ["no_frontmatter", "#{t.path} does not open with a frontmatter block"] unless t.frontmatter_end
        t.includes.each do |block|
          unless blocks.key?(block)
            findings << ["dangling_include", "#{t.path} includes #{block} but #{BLOCKS_SUBDIR}/#{block}.md does not exist"]
          end
          unless (routing[block] || []).include?(t.name)
            findings << ["unauthorized_include",
                         "#{t.path} includes #{block} but #{ROUTING_FILE} does not route #{block} to #{t.name}"]
          end
        end
      end
      routing.each do |block, names|
        unless blocks.key?(block)
          findings << ["dangling_route", "#{ROUTING_FILE} names #{block} but #{BLOCKS_SUBDIR}/#{block}.md does not exist"]
        end
        names.each do |name|
          t = template(name)
          if t.nil?
            findings << ["unknown_agent", "#{ROUTING_FILE} routes #{block} to #{name} but #{name}#{TEMPLATE_EXT} does not exist"]
          elsif !t.includes.include?(block)
            findings << ["missing_include", "#{ROUTING_FILE} routes #{block} to #{name} but #{t.path} never includes it"]
          end
        end
      end
      blocks.each do |block, content|
        findings << ["orphan_block", "#{BLOCKS_SUBDIR}/#{block}.md is named by no entry in #{ROUTING_FILE}"] unless routing.key?(block)
        if content.each_line.any? { |line| line.chomp =~ INCLUDE }
          findings << ["nested_include", "#{BLOCKS_SUBDIR}/#{block}.md contains an @include line; blocks are leaves"]
        end
      end
      (generated_names - templates.map(&:name)).each do |name|
        findings << ["ungenerated_agent", "#{generated_path(name)} has no #{name}#{TEMPLATE_EXT}; every agent here is generated"]
      end
      findings
    end

    # The generated text for one template. Only meaningful once lint is
    # empty: a dangling include would raise here.
    def render(t)
      lines = t.content.lines
      out = lines[0..t.frontmatter_end]
      out << "#{BuildAgents.banner(t.name)}\n"
      lines[(t.frontmatter_end + 1)..-1].each do |line|
        if (m = line.chomp.match(INCLUDE))
          out << with_newline(blocks.fetch(m[1]))
        else
          out << line
        end
      end
      out.join
    end

    private

    def with_newline(text)
      text.end_with?("\n") ? text : "#{text}\n"
    end

    def read_templates
      Dir.glob(File.join(dir, "*#{TEMPLATE_EXT}")).sort.map do |path|
        content = File.read(path)
        Template.new(
          name: File.basename(path, TEMPLATE_EXT),
          path: path,
          content: content,
          includes: content.each_line.map { |l| (m = l.chomp.match(INCLUDE)) && m[1] }.compact,
          frontmatter_end: frontmatter_end(content)
        )
      end
    end

    # Index of the closing fence line, or nil. The opening fence is line 0
    # exactly; the closing one is the next line that is only "---".
    def frontmatter_end(content)
      lines = content.lines
      return nil unless lines[0] && lines[0].chomp =~ FRONTMATTER_FENCE

      idx = lines.drop(1).index { |l| l.chomp =~ FRONTMATTER_FENCE }
      idx && idx + 1
    end

    def read_blocks
      Dir.glob(File.join(dir, BLOCKS_SUBDIR, "*.md")).sort.each_with_object({}) do |path, acc|
        acc[File.basename(path, ".md")] = File.read(path)
      end
    end

    # [routing, error]: routing is {block => [name, ...]}; error is a
    # [code, message] pair when the file is missing or not the shape the
    # header describes, and routing is {} then.
    def read_routing
      path = File.join(dir, ROUTING_FILE)
      return [{}, ["routing_missing", "#{path} does not exist"]] unless File.exist?(path)

      doc = YAML.safe_load(File.read(path))
      shape = "#{ROUTING_FILE} must be a mapping with a `blocks` mapping of block name to a list of agent names"
      return [{}, ["routing_invalid", shape]] unless doc.is_a?(Hash) && (doc["blocks"].nil? || doc["blocks"].is_a?(Hash))

      routing = {}
      (doc["blocks"] || {}).each do |block, names|
        names = [] if names.nil?
        return [{}, ["routing_invalid", shape]] unless block.is_a?(String) && names.is_a?(Array) && names.all? { |n| n.is_a?(String) }

        routing[block] = names
      end
      [routing, nil]
    rescue Psych::SyntaxError => e
      [{}, ["routing_invalid", "#{path} is not valid YAML: #{e.message}"]]
    end
  end

  # Writes content to path through a sibling temp file and a rename, so a
  # reader never sees a half-written agent.
  def self.write_atomically(path, content)
    tmp = "#{path}.#{Process.pid}.tmp"
    File.write(tmp, content)
    File.rename(tmp, path)
  end
end

# The CLI: lint, then either compare (--check) or write (build, honoring
# --dry-run). One envelope on stdout; exit 0 only when nothing was found.
module BuildAgentsCli
  USAGE = "build_agents.rb [--dir DIR] [--check] [--dry-run]"

  module_function

  def run(argv, io: $stdout)
    options = { dry_run: false, dir: BuildAgents::DEFAULT_DIR, check: false }
    parser, options = Cli.build(USAGE, options) do |opts|
      opts.on("--dir DIR", "the agents directory (default: #{BuildAgents::DEFAULT_DIR})") { |v| options[:dir] = v }
      opts.on("--check", "report stale or missing generated files; write nothing") { options[:check] = true }
    end
    args = Cli.parse!(parser, argv)
    unless args.empty?
      warn "unexpected argument: #{args.first}\n\n#{parser}"
      exit 2
    end

    env = Envelope.new(script: "build_agents")
    env.data[:dir] = options[:dir]
    env.data[:mode] = options[:check] ? "check" : "build"
    env.data[:dry_run] = options[:dry_run]
    unless Dir.exist?(options[:dir])
      env.block!(code: "dir_missing", message: "#{options[:dir]} is not a directory")
      return env.emit(io)
    end

    set = BuildAgents::Set.new(options[:dir])
    findings = set.lint
    findings.each { |code, message| env.block!(code: code, message: message) }
    env.data[:blocks] = set.routing.map { |block, names| { name: block, agents: names } }
    env.data[:agents] = []
    return env.emit(io) unless findings.empty?

    set.templates.each do |t|
      path = set.generated_path(t.name)
      rendered = set.render(t)
      current = File.exist?(path) ? File.read(path) : nil
      status =
        if current == rendered then "current"
        elsif current.nil? then "missing"
        else "stale"
        end
      env.data[:agents] << { name: t.name, path: path, status: status }
      next if status == "current"

      if options[:check]
        env.block!(code: "#{status}_generated",
                   message: "#{path} is #{status}; run build_agents.rb --dir #{options[:dir]} to regenerate it")
      else
        env.commands << "write #{path}"
        BuildAgents.write_atomically(path, rendered) unless options[:dry_run]
      end
    end
    env.emit(io)
  end
end

exit BuildAgentsCli.run(ARGV) if __FILE__ == $PROGRAM_NAME
